---
- name: Instala o agente para o Debian
  package:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instala o agente para o RedHat
  package:
    name: puppet-agent
    state: present
  when: ansible_os_family == 'RedHat'

- name: Inicializa o serviço do puppet-agent
  service: 
    name: puppet
    state: started
    enabled: yes
