#- name: Playbook de teste
#  hosts: all
#  tasks:
#    - name: Instala um programa
#      package: 
#        name: htop
#        state: absent


#- name: Playbook de teste
#  hosts: all
#  tasks:
#    - name: Instala o servidor web nas maquinas ubuntu
#      apt:
#        name: apache2
#        state: present
#      when: ansible_os_family == 'Debian'
#
#    - name: Instala o servidor web nas maquinas redhat
#      yum:
#        name: httpd
#        state: present
#      when: ansible_os_family == 'RedHat' 
#
#    - name: Copia o index.html
#      copy:
#        src: index.html
#        dest: /var/www/html/index.html
# 
#    - name: Reinicia o servidor web
#      service: 
#        name: httpd
#        state: restarted
#      when: ansible_os_family == 'RedHat'
       
- name: Playbook de teste
  hosts: all
  tasks:
    - name: Desinstala o servidor web nas maquinas ubuntu
      apt:
        name: apache2
        state: absent
      when: ansible_os_family == 'Debian'

    - name: Desinstala o servidor web nas maquinas redhat
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == 'RedHat'

